Traceback (most recent call last):
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/nbclient/client.py", line 778, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
    result = await obj
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/jupyter_client/channels.py", line 315, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/anaconda3/envs/env_st/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/nbclient/client.py", line 1001, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/nbclient/client.py", line 802, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/nbclient/client.py", line 852, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['from sklearn.metrics import make_scorer, mean_absolute_error', '', "os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # Esto ignorará todos los logs de info y warnings.", '', '# Define the LSTM network architecture']
...
['# Resultados del Grid Search', 'print(f"Mejor función de activación: {grid_result.best_params_[\'activation\']}")', 'print(f"Mejor número de epocas: {grid_result.best_params_[\'epochs\']}")', 'print(f"Mejor Longitud de paso μ (optimizer): {grid_result.best_params_[\'optimizer\']}")', 'print(f"Mejor Puntuación: {grid_result.best_score_}")']
-------------------

