Traceback (most recent call last):
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/anaconda3/envs/env_st/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/env_st/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
best_p = gbest_order[0]
best_q = gbest_order[1]

print(f"Mejor p: {best_p}, Mejor q: {best_q}")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[186], line 1[0m
[0;32m----> 1[0m best_p [38;5;241m=[39m [43mgbest_order[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m
[1;32m      2[0m best_q [38;5;241m=[39m gbest_order[[38;5;241m1[39m]
[1;32m      4[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mMejor p: [39m[38;5;132;01m{[39;00mbest_p[38;5;132;01m}[39;00m[38;5;124m, Mejor q: [39m[38;5;132;01m{[39;00mbest_q[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mTypeError[0m: 'NoneType' object is not subscriptable

